version: "3"

networks:
  backend:
    driver: bridge

services:
  master:
    container_name: redis-master
    build:
      context: "./master"
    ports:
      - 6300:6379
    networks:
      - backend

  slave1:
    container_name: redis-slave-1
    build:
      context: "./slave1"
    ports:
      - 6301:6379
    depends_on:
      - master
    networks:
      - backend

  slave2:
    container_name: redis-slave-2
    build:
      context: "./slave2"
    ports:
      - 6302:6379
    depends_on:
      - master
    networks:
      - backend

  sentinel1:
    container_name: redis-sentinel-1
    build:
      context: "./sentinels/sentinel-1"
    ports:
      - 16379:26379
    depends_on:
      - master
    networks:
      - backend


  sentinel2:
    container_name: redis-sentinel-2
    build:
      context: "./sentinels/sentinel-2"
    ports:
      - 26379:26379
    depends_on:
      - master
    networks:
      - backend

  sentinel3:
    container_name: redis-sentinel-3
    build:
      context: "./sentinels/sentinel-3"
    ports:
      - 36379:26379
    depends_on:
      - master
    networks:
      - backend
